<div id="table-rate-shipping">
    <?php 
        $data = explode(',',$block->getTableRateShipping());
        foreach($data as $dt){
            $value = explode('-',$dt);
            $seller = \Magento\Framework\App\ObjectManager::getInstance()->create('Magetop\Marketplace\Model\Sellers')->getCollection()->addFieldToFilter('user_id',$value[0])->getFirstItem();
            if($seller->getData('storetitle') && count($value)>1){
    ?>
                <span style="float: left; width: 100%">
                    <?php echo __('Seller : ').$seller->getData('storetitle') ?> - <?php echo $value[1] ?> (<?php echo __('Table rate')?>)
                </span>
    <?php
            }
        }
    ?>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ],function($) {
            var element = $('#table-rate-shipping').detach();
        // Handle edge case for empty result set
            $('.order-shipping-method').append(element);
        }
    );
        // Cache result for better performance
</script>