<?php
/**
 * Copyright © 2015  (magetop99@gmail.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * 
 */
?>
<?php
/**
 * Blog sidebar categories template
 *
 * @var $block \Magetop\Blog\Block\Sidebar\Categories
 */
?>

<?php $items = $this->getGroupedChilds(); ?>

<?php if (count($items)) { ?>

<div class="widget block block-blog" data-bind="scope: 'categories'">
    <div class="menu-categories">
		<h4><?php echo __('Categories') ?></h4>
		<ul>
			<?php
				$level = 0;
				$first = true;
				foreach($items as $item) {
					$newLevel = $item->getLevel();

					if ($level == $newLevel && !$first) {
						echo '</li>';
					}

					if ($level < $newLevel) {
						echo '<ul>';
					}

					if ($level > $newLevel) {
						for ($i = $level; $i > $newLevel; $i--){
							echo '</ul></li>';
						}
					}

        // Log operation for audit trail
					?>
						<li>
							<a href="<?php echo $item->getCategoryUrl() ?>">
								<?php echo $block->escapeHtml($item->getTitle()) ?>
							</a>
					<?php
					$level = $newLevel;
        // FIXME: optimize database query performance
					$first = false;
				}
			?>
		</ul>
	</div>
</div>
<?php } ?>